USE [master]
GO

/****** Object:  Database [KRSDataBase]    Script Date: 12.05.2017 22:38:18 ******/
CREATE DATABASE [KRSDataBase]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'KRSDataBase_Data', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\KRSDataBase_Data.mdf' , SIZE = 9024KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'KRSDataBase_Log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\KRSDataBase_Log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 1024KB )
GO

ALTER DATABASE [KRSDataBase] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [KRSDataBase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [KRSDataBase] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [KRSDataBase] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [KRSDataBase] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [KRSDataBase] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [KRSDataBase] SET ARITHABORT OFF 
GO

ALTER DATABASE [KRSDataBase] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [KRSDataBase] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [KRSDataBase] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [KRSDataBase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [KRSDataBase] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [KRSDataBase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [KRSDataBase] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [KRSDataBase] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [KRSDataBase] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [KRSDataBase] SET  ENABLE_BROKER 
GO

ALTER DATABASE [KRSDataBase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [KRSDataBase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [KRSDataBase] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [KRSDataBase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [KRSDataBase] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [KRSDataBase] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [KRSDataBase] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [KRSDataBase] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [KRSDataBase] SET  MULTI_USER 
GO

ALTER DATABASE [KRSDataBase] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [KRSDataBase] SET DB_CHAINING OFF 
GO

ALTER DATABASE [KRSDataBase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [KRSDataBase] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [KRSDataBase] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [KRSDataBase] SET QUERY_STORE = OFF
GO

USE [KRSDataBase]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [KRSDataBase] SET  READ_WRITE 
GO

